version: '3.3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      #- 8088:80
      - 80:80

  # docker run -d -p 8080:8080 --name erddap axiom/docker-erddap
  erddap:
    user: root:4504
    container_name: erddap
    build: ./erddap
    volumes:
     - ./erddap/erddap_data:/erddapData
     - ./erddap/content:/usr/local/tomcat/content/erddap
     # === ERDDAP dataset mounts==============================================
     # NOTE: paths must match "fileDir" paths in erddap/content/datsets.xml
     - /srv/imars-objects:/srv/erddap-datasets:ro,slave
     # =======================================================================
    restart: unless-stopped
    ports:
      - 8080:8080
 # sudo docker exec -it erddap bash -c "cd /usr/local/tomcat/webapps/erddap/WEB-INF && bash GenerateDatasetsXml.sh -verbose"

  grafana:
      container_name: grafana
      image: grafana/grafana:6.7.3
      ports:
          - 3000:3000
      environment:
          - "GF_INSTALL_PLUGINS=alexandra-trackmap-panel,https://github.com/USF-IMARS/grafana-erddap/releases/download/1.0.0/grafana-erddap.zip;grafana-erddap"
          - GF_PATHS_PROVISIONING=/grafana_provisioning
      volumes:
          - ./grafana/provisioning:/grafana_provisioning

  influxdb:
        container_name: influxdb
        image: influxdb:1.8
        ports:
            - 8086:8086  # HTTP API
            - 2003:2003  # graphite API
        volumes:
            # init the db by putting .sh or .iql files in /docker-entrypoint-initdb.d
            # this should inlcude adding a read-only user for grafana
            - ./influxdb/initdb:/docker-entrypoint-initdb.d
            # docker data volume:
            - ./influxdb/data_volume:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=fwc_coral_disease
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_USER=influx_admin
            - INFLUXDB_READ_USER=grafana
            - INFLUXDB_WRITE_USER=telegraf
  ftp_ingester:
      container_name: ftp_ingester
      build: ./ftp_ingester
      ports:
          - 20:20
          - 21:21
      volumes:
          - ./ftp_ingester/vsftpd_home:/home/vsftpd
          - ./ftp_ingester/vsftpd_logs:/var/log/vsftpd
      environment:
          - "FTP_USER=imars"
