{
 "title": "FWC Coral Disease Dash",
 "time": { "from": "2013-01-01T05:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "Locations", "query": "SLI,PBI,PEV,MIA,MOL,SOM,SUG,KW" },
   {
    "name": "Bouys",
    "query": "BOBALLEN,BUTTERNUT,LITTLERABBIT,PETERSON,WHIPRAY"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 0 },
   "content": "![map of sub-regions](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWCdb_map_v4.png)"
  },
  {
   "title": "General Information",
   "type": "text",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 0 },
   "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_DB_imagepanel_sized.png)\n\nSelect a specific location using the \"Locations\" dropdown menu at left.\n\nDisplay mean, climatology, or anomalies of extracted satellite data using the \"Time-series display metric\" menu at left.\n\nThe range of the displayed time period can be adjusted at top right.\n\nLocations of extracted satellite data:\n* SLI: St. Lucie River inlet\n* PBI: Palm Beach inlet\n* PEV: Port Everglades\n* MIA: Miami\n* MOL: Molasses Reef\n* SOM: Sombrero Key\n* SUG: Sugarloaf Key\n* KW: Key West\n\n"
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "VIIRS Chlorophyll-a 7-day Anomaly Images",
   "type": "erddap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "VIIRS nighttime SST 7-day Anomaly Images",
   "type": "erddap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "MODIS-Aqua Algal Bloom Index 7-Day Anomaly Images (W/m^2/um/sr)",
   "type": "erddap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "VIIRS Reflectance at 671nm 7-day Anomaly Images (turbidity proxy)",
   "type": "erddap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "VIIRS Reflectance at 671nm 7-day Anomaly Images (turbidity proxy)",
   "type": "erddap-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Cumulative percent of sampling sites infected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Coral Disease 2014",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 59 },
   "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2014001_2014365_CD_obs.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2014001_2014365_CD_obs.png\"\n></img>\n</a>"
  },
  {
   "title": "Coral Disease 2015",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 59 },
   "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2015001_2015365_CD_obs.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2015001_2015365_CD_obs.png \"\n></img>\n</a>"
  },
  {
   "title": "Coral Disease 2016",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 59 },
   "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2016001_2016365_CD_obs.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2016001_2016365_CD_obs.png\"\n></img>\n</a>"
  },
  {
   "title": "Coral Disease 2017",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 59 },
   "content": "<a \n  href=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2017001_2017365_CD_obs.png\"\n><img \n  src=\"https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_2017001_2017365_CD_obs.png\"\n></img>\n</a>"
  },
  {
   "title": "VIIRS SSTN Anomaly @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"viirs_sstn\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Chlorophyll-a @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"viirs_chlor_a\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "MODIS ABI Anomaly @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"modis_abi\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "VIIRS Rrs 671 Anomaly @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"viirs_rrs_671\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Kd_490 (water clarity proxy) @ $Locations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modis_abi",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"viirs_kd_490\"\nWHERE (\"location\" =~ /^$Locations$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "anomaly" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$Locations$/" }
     ]
    }
   ]
  },
  {
   "title": "Gage height from rivers on Florida's east coast (sum of gage height from rivers shown by red circles on map)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "river_discharge",
     "query": "SELECT mean(\"mean\") AS mean FROM \"river_discharge\"\nWHERE (\"location\" = 'FWCdb_EFL') AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In-situ salinity (psu) from selected buoys",
   "type": "graph",
   "description": "TODO: add other bouys to overview map?",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "river_discharge",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"bouy_sal\"\nWHERE (\"location\" =~ /^$Bouys$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In-situ salinity (psu) from selected buoys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "river_discharge",
     "query": "SELECT mean(\"anomaly\") AS anomaly FROM \"bouy_temp\"\nWHERE (\"location\" =~ /^$Bouys$/) AND anomaly!=-999 AND $timeFilter \nGROUP BY time($__interval),\"location\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "This work supported by",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 93 },
   "content": "![logo image](https://raw.githubusercontent.com/marinebon/mbon-dashboard-server/master/static_files/FWC_DB_imagepanel_sized.png))\n"
  }
 ]
}